/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseCard: typeof import('./components/base/BaseCard.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoadingSpinner: typeof import('./components/common/LoadingSpinner.vue')['default']
    PredictionCard: typeof import('./components/predictions/PredictionCard.vue')['default']
    PredictionGrid: typeof import('./components/predictions/PredictionGrid.vue')['default']
    PredictionList: typeof import('./components/predictions/PredictionList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StationSelect: typeof import('./components/station/StationSelect.vue')['default']
    TrainArrival: typeof import('./components/TrainArrival.vue')['default']
  }
}
